spring.application.name=collage

# DB configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/collageDb
spring.datasource.username=postgres
spring.datasource.password=YOUR_DB_PASSWORD

# Hibernate
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

# Run data.sql after Hibernate creates tables
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true