spring.application.name=collage

# DB configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/collageDb
spring.datasource.username=postgres
spring.datasource.password=raman1234

# Hibernate
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

## Run data.sql after Hibernate creates tables
#spring.sql.init.mode=always
#spring.jpa.defer-datasource-initialization=true


jwt.secretKey=k7f2Q9vL4xN8mR3pT6yW1sZ5aB0cD9eF2gH7jK4nP8qV6wX3rM1tY5uI0oA9sE6